// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      includereplace: {
        dist: {
          options: {
            prefix: '@@',
            suffix: ''
          },
          src: 'src/html/*.html',
          dest: 'build/html/'
        }
      },
      clean: {
        files: ["build/html/_*.html", "build/*.js"]
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: "src/img/",
              src: ["**"],
              dest: "build/img"
            },{
              expand: true,
              cwd: "src/fonts",
              src: ["**"],
              dest: "build/fonts"
            }, {
              expand: true,
              cwd: "src/features/",
              src: "**",
              dest: "build/features/"
            }, {
              expand: true,
              cwd: "src/js",
              src: ["**"],
              dest: "build/js"
            }
          ]
        }
      },
      watch: {
        files: ["src/html/*.html", "src/features/", "src/js/*.js", "src/img/icons*.png"],
        tasks: ["includereplace", "copy", "clean"]
      }
    });
    require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
    grunt.registerTask("default", ["watch"]);
    return grunt.registerTask("a", ["clean", "includereplace", "copy"]);
  };

}).call(this);
