// Generated by CoffeeScript 1.6.2
(function() {
	module.exports = function(grunt) {

		grunt.initConfig({
			// Склеиваем
			concat: {
				main: {
					src: [
						'src/js/libs/jquery.js',
						'src/js/libs/cycle.js',
						'src/js/libs/jquery.fancybox.pack.js',
						'src/js/libs/jquery.flexslider.js',
						'src/js/common.js'
					],
					dest: 'build/js/scripts.js'
				}
			},

			// Сжимаем
			uglify: {
				main: {
					files: {
						// Результат задачи concat
						'build/js/scripts.min.js': '<%= concat.main.dest %>'
					}
				}
			},

			includereplace: {
				dist: {
					options: {
						prefix: '@@',
						suffix: ''
					},
					src: 'src/html/*.html',
					dest: 'build/html/'
				}
			},

			clean: {
				files: ["build/html/_*.html", "build/js/*.js", "!build/js/*.min.js"]
			},

			copy: {
				main: {
					files: [
						{
							expand: true,
							cwd: "src/img/",
							src: ["**"],
							dest: "build/img"
						},
						{
							expand: true,
							cwd: "src/html/*.html",
							src: ["**"],
							dest: "build/html/"
						},{
							expand: true,
							cwd: "src/fonts",
							src: ["**"],
							dest: "build/fonts"
						}
					]
				}
			},

			watch: {
				files: ["src/html/*.html", "src/features/", "src/js/*.js", "src/js/libs/*.js", "src/img/icons*.png"],
				tasks: ['includereplace', 'concat', 'uglify', 'copy', 'clean']
			}

		});
		require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);

		// Загрузка плагинов, установленных с помощью npm install
		// grunt.registerTask("default", ["watch"]);
		grunt.loadNpmTasks('grunt-contrib-watch');
		grunt.loadNpmTasks('grunt-contrib-concat');
		grunt.loadNpmTasks('grunt-contrib-uglify');

		// Задача по умолчанию
		grunt.registerTask('default', ['watch']);
		return grunt.registerTask("a", ['includereplace', 'concat', 'uglify', 'copy', 'clean']);

	};

}).call(this);
